### ISSUE TITLE
Introduction : Motivation (1.1 - 1.3)

### ISSUE THREAD

**Issue by eyeamkd** [eyeamkd/disha#101]
- 1.1.1 Overview of Existing System  
- 1.1.2 Overview of Proposed System   
- 1.1.3 System Features

**Comment by eyeamkd** [comment]
Updated section 1.1

**Comment by eyeamkd** [comment]
@akylus completed, please check.

**Comment by akylus** [comment]
Good job. All good. closing the issue.
