### ISSUE TITLE
Introduction (1.3 - 1.5) 

### ISSUE THREAD

**Issue by eyeamkd** [eyeamkd/disha#102]
- 1.3 Objective 
- 1.4 Scope 
-  1.5 Organization

**Comment by akylus** [comment]
Completed writing anna, please review the content so that we can close this issue. 
I have also written the **Problem Definition i.e., 1.2** so please check that too.

**Comment by eyeamkd** [comment]
Okay, wil do

**Comment by eyeamkd** [comment]
My Opinion : 
Section 1.3
- `inculcate good practices of coding` --> internships and projects in the applications can be for varied branches of engineering other than CS.  
- How about including a point about connecting the people who belong to VBIT

**Comment by akylus** [comment]
Yes, will add & change

**Comment by akylus** [comment]
Added. Pls check & if good close this issue

**Comment by akylus** [comment]
@eyeamkd pls review & close
