### ISSUE TITLE
Introduction Preface

### ISSUE THREAD

**Issue by eyeamkd** [eyeamkd/disha#103]
Preface of the Introduction Section in DISHA's Documentation Template 
About 3 paragraphs worth of content to be written 
with at least 10-15 lines each 

Contents: 
- Why a platform like DISHA is essential to the students of VBIT @eyeamkd 
- Applications present that resemble DISHA @eyeamkd 
- What Impact would DISHA produce in VBIT @akylus 
- Future Scope of DISHA @akylus

**Comment by eyeamkd** [comment]
I deduced those contexts from the template. 
Feel free to change them

**Comment by akylus** [comment]
added my part. pls check

**Comment by eyeamkd** [comment]
```if necessary, from the community. Integration with the Management’s data can help students to monitor their academic performance``` 
didn't get this point, when did we ever think of including acads on DISHA?

**Comment by eyeamkd** [comment]
Completed my part too, will close if you're okay with it @akylus

**Comment by akylus** [comment]
> `Integration with the Management’s data can help students to monitor their academic performance`
> didn't get this point, when did we ever think of including acads on DISHA?

since u told future scope, I added that. Nothing else struck me. Lemme know if u want me to remove it

**Comment by eyeamkd** [comment]
Future scope can be our ambiguous issues, i added 2 new ones today. You are welcome to write about those in the doc

**Comment by akylus** [comment]
done, added. 
Regarding your part - I don't think it's wise to mention VBIT in the documentation. It's supposed to be general. Content-wise it's fine

**Comment by eyeamkd** [comment]
I removed all instances of VBIT.
closing now, re-open if required
