### ISSUE TITLE
Literature Survey | Alumni Portal 

### ISSUE THREAD

**Issue by eyeamkd** [eyeamkd/disha#104]
- Go through alumni pages 
- HBS
- MIT 
- CBIT 
- IITB

**Comment by eyeamkd** [comment]
Completed my part @akylus . 
Lemme know if you feel the content is very short.

**Comment by akylus** [comment]
Increase the content to fit one page

**Comment by eyeamkd** [comment]
Okay!

**Comment by eyeamkd** [comment]
Made the changes @akylus, please let me know what you think. 
if okay, feel free to close the issue

**Comment by akylus** [comment]
Great job!
