### ISSUE TITLE
Your DSpaces is giving an error

### ISSUE THREAD

**Issue by akylus** [eyeamkd/disha#107]

**Comment by eyeamkd** [comment]
anna description?

**Comment by akylus** [comment]
My apologies. It's the same issue that had popped up while discussing on our call after the project finally worked on my system. I thought you would get it.
Attaching a screenshot link. [https://imgur.com/a/w5vWEy5](here)

**Comment by eyeamkd** [comment]
I don't seem to recollect but anyway, will check and let yk
