### ISSUE TITLE
Conclusion | Documentation

### ISSUE THREAD

**Issue by eyeamkd** [eyeamkd/disha#117]
-  if implemented how would DISHA help VBITians 
- What changes can DISHA bring in VBIT 
- how will every feature of DISHA contribute to the change

**Comment by akylus** [comment]
I've written the conclusion anna, check once

**Comment by akylus** [comment]
@eyeamkd

**Comment by eyeamkd** [comment]
Yes anna, we'll finish doc stuff, scrum at 9?

**Comment by eyeamkd** [comment]
Checked! Great Job!
