### ISSUE TITLE
Future Enhancements 

### ISSUE THREAD

**Issue by eyeamkd** [eyeamkd/disha#118]
-  Mentoring board 
-  Alumni Job board 
-  Donation Feature 
-  PWA support  
-  Chat feature  
- Reunion / activities planner

**Comment by eyeamkd** [comment]
Added only the three, should be enough.
lemme know if you want more. 

Please check the document @akylus

**Comment by akylus** [comment]
perfect. in the end if we face a shortage on the number of pages, I'll reopen the issue
