### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by sanath1599** [eyeamkd/disha#149]
Website loads blank with the following error
![image](https://user-images.githubusercontent.com/20601717/82738922-07fea300-9d59-11ea-98d6-5b93b54d7919.png)

**Comment by eyeamkd** [comment]
Seems to be working fine for me. Can you recheck and let us know? 
![Screenshot 2020-05-25 at 11 49 33 AM](https://user-images.githubusercontent.com/31094327/82784325-eea34700-9e7d-11ea-83d6-372da47aa69f.png)
