### ISSUE TITLE
Authentication | Sign Up Page

### ISSUE THREAD

**Issue by eyeamkd** [eyeamkd/disha#25]
Build the Sign In/ Sign Up functionality of the Disha Authentication System. 

The Auth should be taking place in two stages :
1. User registers himself/ herself for the application and fills the necessary details : 
                a) Roll Number 
                b) Year, Section 
                c) Social Profile Link  
                d) Email 
                e) Registered Phone Number  
2. Account Confirmation by College Admin

**Comment by akylus** [comment]
Completed!
