### ISSUE TITLE
FirebaseError after creating new post. Unable to create new posts.

### ISSUE THREAD

**Issue by s3p1ol** [eyeamkd/disha#77]
I'm trying to create a new post. After adding the tags and clicking on create new posts it gives me this error

FirebaseError: Function DocumentReference.set() called with invalid data. Unsupported field value: undefined (found in field authorRollNumber)

![disha-error jpg](https://user-images.githubusercontent.com/36568239/77320121-fd626600-6d35-11ea-8075-6660da1a80b8.png)

(Pic related)

**Comment by akylus** [comment]
Fixed the issue. You may check now! Closing this issue.
